### ISSUE TITLE
news: rebuild matches when user adds or removes an address

### ISSUE THREAD

**Issue by lucasvanhalst** [our-city-app/mobicage-backend#200]
Currently the matches are only created when a news item is created or saved, but they should be created when the user adds/removes/updates an address too.

**Comment by RubenMattan** [comment]
Just had a discussion with Tom about it and he thinks we shouldn't do this. Lets discuss with some more people.

**Comment by RubenMattan** [comment]
I'm pro adding items, but nog removing items

Reason: 
- some location based news items can be interesting because they talk about the future (road works, ...)
- The user removes the location because he doesn't want any news updates, you already saw these old news items so removing them would be weird

**Comment by RubenMattan** [comment]
Bart says yes to both, but limit adding old items on time (1 to 3 month or so)

**Comment by RubenMattan** [comment]
Not relevant anymore
