### ISSUE TITLE
Error in privacy policy page because language headers couldn't be parsed

### ISSUE THREAD

**Issue by lucasvanhalst** [our-city-app/mobicage-backend#60]
---

Migrated from https://github.com/rogerthat-platform/rogerthat-backend/issues/519
Originally created by @bart-at-mobicage on *Mon, 11 Jun 2018 08:43:17 GMT*

---
```
/legal?doc=privacy-policy

2018-06-11 08:10:52.843 CEST
Could not parse language header. (/base/data/home/apps/e~rogerthat-server/20180608t091910.410288129468509991/add_1_monkey_patches.py:128)
Traceback (most recent call last):
  File "/base/data/home/apps/e~rogerthat-server/20180608t091910.410288129468509991/rogerthat/templates/__init__.py", line 79, in get_languages_from_header
    qualifier = items[1].split("=")[1]
IndexError: list index out of range
```

**Comment by abom** [comment]
This must be a malformed value or maybe another [accept-extension ](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.1 )instead of the quality factor without `=` sign?

It can only happens with values like:
`en;q` or `en;q,ar` or even `en;` (the equal sign is not there).

I added as simple fix to check for **q** before getting the value of it.
